### ISSUE TITLE
Loading/saving masks in pixel coordinates

### ISSUE THREAD

**Issue by jo-moeller** [European-XFEL/EXtra-foam#116]
We would need the masks to be saved and loaded in the same shape as the detector data. As for example for AGIPD as (16,512,128) array. This would make the masks reusable, even if the geomertry of the quadrants changes. And in general, a bad pixel stays bad, even if the quadrant moves.

Also, it would make EXtra-foam masks compatible with other programs, as for example the the ADU_histogram device in Karabo.

**Comment by zhujun98** [comment]
Do you have a sample file for the mask? 

I would like to make you realize that in the deployed new version 0.8.1, there is an option in the `Geometry` panel to select assembler. Unlike LPD and DSSC, now the default assembler for AGIPD is still `EXtra-geom` and I will switch it to `EXtra-foam` at some point. The assembler in `EXtra-foam` is implemented in C++ and is 5 - 10 times faster than `EXtra-geom` on the online cluster.

As the C++ assembler now support all the three modular detectors, it is time to implement the `universal` mask that you requested.

**Comment by jo-moeller** [comment]
You can find an example mask at /gpfs/exfel/exp/MID/201901/p002542/usr/Software/mask.npy

**Comment by zhujun98** [comment]
I just deployed a test version 0.8.3dev at `EXtra-foam/alpha`. Can you test it when you have time? Thank you!

**Comment by zhujun98** [comment]
We can reopen the issue or start another one if you find any bug or need some additional features.

**Comment by zhujun98** [comment]
Forgot to mention that I also updated the documentation

https://extra-foam.readthedocs.io/en/latest/image_tool.html#mask-panel

**Comment by jo-moeller** [comment]
Hi,
there might be still an issue. I have selected this geometry: /gpfs/exfel/exp/MID/202022/p002693/usr/Software/geom_20200912.geom with Assembler: extra-foam.
When I now create a mask in extra-foam, save it and reload it, I get the follwing error:
ERROR- Shape of the image mask (1259,1092) is different form the image (1357,1195)!

**Comment by zhujun98** [comment]
Yes, there is something not easy to fix in order to synchronize the mask in the processors and the GUI sides. If I still remember correctly, you will need to keep the image tool showing the geometry panel and wait for the new mask to get updated. Otherwise, there is a chance to get the error you mentioned if you switched to other pannels.
